// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    document_verification
    (
        init => init
        upgrade => upgrade
        registerDocument => register_document
        verifyDocument => verify_document
        revokeDocument => revoke_document
        getUserDocuments => get_user_documents
        getTotalDocuments => get_total_documents
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
